---
- name: setting varibles
  set_fact:
    java_version: 8u411

- name: Download java
  include_role:
    name: artifacts-upload-gcp
    tags:
      - download
    vars:
      artifact: "igot-artifact/infra/java/jre-{{java_version}}-linux-x64.tar.gz"
      artifact_path: "/tmp/jre-{{java_version}}-linux-x64.tar.gz"

- name: Uncompressing and copying to system path
  unarchive:
    src: /tmp/jre-{{java_version}}-linux-x64.tar.gz
    dest: /opt/jre-{{java_version}}
    remote_src: yes
    keep_newer: yes
  register: tar

- name: Updating java jre to system path
  shell: update-alternatives --install /usr/bin/java java /opt/jre-{{java_version}}/bin/java 9999
  when: tar.changed

- name: Checking java version
  shell: java -version
  register: java

- name: Java version
  debug:
    var: java.stderr
