analytics_user: analytics
analytics_group: analytics
analytics_user_home: /home/{{analytics_user}}
sbin_path: "{{ analytics_user_home }}/sbin"

gs_base_path: "secor-{{ env }}"
s3_base_path: "secor-{{ env }}"
s3_container_name: "{{ cephs3_dp_storage_container | default('') }}"
s3_access_key: "{{ cephs3_storage_key | default('') }}"
s3_secret_key: "{{ cephs3_storage_secret | default('') }}"
s3_endpoint: "{{ cephs3_storage_endpoint | default('') }}"
# s3_endpoint: "https://static.karmyogiprod.nic.in"
s3_region: "{{ cephs3_storage_region | default('us-east-1') }}"
s3_path_style_access: "true"

telemetry_ingestion_topic: "{{ env }}.telemetry.ingestion"

secor:
  properties: ['secor.common', 'secor', 'secor.partition', 'log4j']
  artifact_dir: /mount/secor

secor_service_name:
  failed-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.failed.backup"
    base_path: "failed"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.failed"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9997"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Failed Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  raw-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.raw.backup"
    base_path: "raw"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.raw"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9994"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Raw Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  unique-telemetry-backup:
    consumer_group: "{{ env }}.telemetry.unique.backup"
    base_path: "unique/raw"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.unique"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9969"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Unique Telemetry Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  derived-denorm-events-backup:
    consumer_group: "{{ env }}.summary.backup"
    base_path: "telemetry-denormalized/summary"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.druid.events.summary"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9992"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Denormalized Summary Events Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  extractor-failed-backup:
    consumer_group: "{{ env }}.extractor.failed.backup"
    base_path: "extractor-failed"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.extractor.failed"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9989"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Extractor failed events backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  assess-raw-events-backup:
    consumer_group: "{{ env }}.telemetry.assess.raw"
    base_path: "telemetry-raw-assess"
    timestamp_key: "syncts"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.telemetry.assess.raw"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(',')}}"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9986"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Telemetry raw assess events backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  learning-events-backup:
    consumer_group: "{{ env }}.learning.graph.events.backup"
    base_path: "learning-events"
    timestamp_key: "createdOn"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.learning.graph.events"
    kafka_broker_host: "{{groups['ingestion-cluster-kafka']|join(':9092,')}}:9092"
    zookeeper_quorum: "{{groups['ingestion-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9980"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Learning Events Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "56"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  issue-certificate-events-backup:
    consumer_group: "{{ env }}.issue.certificate.request.backup"
    base_path: "issue-certificate-events"
    timestamp_key: "ets"
    fallback_timestamp_key: "@timestamp"
    topic: "{{ env }}.issue.certificate.request"
    kafka_broker_host: "{{groups['ingestion-cluster-kafka']|join(':9092,')}}:9092"
    zookeeper_quorum: "{{groups['ingestion-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9976"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Issue Certificate Events Backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "55"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"
  pipeline-metrics-backup:
    consumer_group: "{{ env }}.pipeline_metrics"
    base_path: "data-pipeline-metrics"
    timestamp_key: "metricts"
    fallback_timestamp_key: "metricts"
    topic: "{{ env }}.pipeline_metrics"
    kafka_broker_host: "{{groups['processing-cluster-kafka']|join(':9092,')}}:9092"
    zookeeper_quorum: "{{groups['processing-cluster-zookeepers']|join(':2181,')}}:2181"
    max_file_size: "100000000"
    max_file_age: "14400"
    ostrich_port: "9991"
    partition_prefix_enabled: "false"
    partition_prefix_key: ""
    partition_prefix_mapping: "{}"
    output_file_pattern: "{partition}-{kafkaPartition}-{currentTimestamp}.json"
    service_description: "Pipeline metrics backup"
    service_monitor_schedule_hr: "23"
    service_monitor_schedule_min: "50"
    message_channel_identifier: ""
    message_parser: "com.pinterest.secor.parser.PatternDateMessageParser"